### ISSUE TITLE
Add Java examples

### ISSUE THREAD

**Issue by ensean** [bigfix/restapi-examples#2]
Is it possible to translate curl command to java code sample?

Sine you may know that java more popular when integration project is developed.

**Comment by ottumm** [comment]
It's a reasonable request, but, honestly, I don't think we'll be able to expand our language samples any time soon. The point of providing curl examples was to show the exact HTTP request formats. Developers should be able to translate those into any language/framework that can perform HTTP requests.

**Comment by ensean** [comment]
Thanks a lot
